### ISSUE TITLE
No git wiki 

### ISSUE THREAD

**Issue by rgreiser20** [xxk-i/xxk-i.github.io#3]
# Issue
No wiki for this websites git repository

# Steps to reproduce
1. Navigate to github page
2. Look for wiki tab in the navigation bar

# Impacts of issue
Unable to develop a clear understanding of the repo and the inner workings of how to work with code inside the repository

# Potential Resolutions
Add an approximately 20-page wiki to thoroughly document the design process behind the code and any potential additions to the website in the future

**Comment by xxk-i** [comment]
wokepedia

**Comment by xxk-i** [comment]
Labeled as duplicate of closed issue
