### ISSUE TITLE
Wiki not visible

### ISSUE THREAD

**Issue by rgreiser20** [xxk-i/xxk-i.github.io#4]
Color is not safe for screen readers (blind people). Please revisit your code. Thanks.

Also, this does not match our styling standards, as listed in the repository wiki. Thanks.

_Originally posted by @xxk-i in https://github.com/xxk-i/xxk-i.github.io/issues/2#issuecomment-1360759283_
      
### As stated in the referenced comment above, there is an apparent wiki for this repo however it is not visible to public users, please fix.

**Comment by xxk-i** [comment]
Users must complete a RECaptcha, background check, and iris approval to see the wiki (Blue-eyes only, as listed in the "requirements" page of the wiki, please review it).

**Comment by rgreiser20** [comment]
oh

**Comment by xxk-i** [comment]
(Blond hair is also a requirement, again listed in the Wiki)

**Comment by xxk-i** [comment]
comment

**Comment by xxk-i** [comment]
Reopened so I could once again, close your issue.

Please stop making issues.

**Comment by xxk-i** [comment]
You probably are struggling to get wiki access because you do not know how to right click.

Please read up on the "Mouse interaction" section in the Wiki for more information in using right click among different devices.

**Comment by rgreiser20** [comment]
`print('no');`

**Comment by xxk-i** [comment]
This is not up to styling standards as I've stated before. Please update your comment.

**Comment by rgreiser20** [comment]
> `print('no');`

Code has been edited per the style guidelines

**Comment by xxk-i** [comment]
This code is still missing proper annotations. Have you *actually read* the entire styling section of the wiki? I don't see a thread opened in the discord.

**Comment by xxk-i** [comment]
I've also checked my fax. You have not contacted the "Plan C" fax number either.

**Comment by rgreiser20** [comment]
- closed

**Comment by xxk-i** [comment]
Last Christmas I gave you my heart
But the very next day you gave it away
This year, to save me from tears
I'll give it to someone special
Last Christmas I gave you my heart
But the very next day you gave it away
This year, to save me from tears
I'll give it to someone special
Once bitten and twice shy
I keep my distance, but you still catch my eye
Tell me baby, do you recognize me?
Well, it's been a year, it doesn't surprise me
Happy Christmas, I wrapped it up and sent it
With a note saying "I love you", I meant it
Now I know what a fool I've been
But if you kissed me now, I know you'd fool me again
Last Christmas I gave you my heart
But the very next day you gave it away
This year, to save me from tears
I'll give it to someone special
Last Christmas I gave you my heart
But the very next day you gave it away
This year, to save me from tears
I'll give it to someone special
Ooh
Oh, oh, baby
A crowded room, friends with tired eyes
I'm hiding from you and your soul of ice
My God, I thought you were someone to rely on
Me? I guess I was a shoulder to cry on
A face on a lover with a fire in his heart
A man under cover, but you tore me apart
Oh, oh now I've found a real love
You'll never fool me again
Last Christmas I gave you my heart
But the very next day you gave it away
This year, to save me from tears
I'll give it to someone special, special
Last Christmas I gave you my heart
But the very next day you gave it away
This year, to save me from tears
I'll give it to someone special
Special
A face on a lover with a fire in his heart (I gave you mine)
A man under cover but you tore him apart
Maybe next year I'll give it to someone
I'll give it to someone special
Special
So long

Do these mean anything to you? It's at the end of the table of wiki contents. As listed in the "Table of contents wiki wiki"
